random_seed: 42
data:
  image_folder: "/home/ilyabushmakin/Documents/Projects/DataStorage/kaggle_personal/LargeRDataset"
  image_metadata_db: "postgresql+psycopg2://ilbumi:aaaa@localhost/main"
  image_size: 224
  batch_size: 32
  num_workers: 12
  tag_variance_threshold: 0.04
model:
  model_name: "swsl_resnext50_32x4d"
  dropout: 0.1
  weight_decay: 0.0000
  learning_rate: 0.1
  warmup_steps: 1
  finetuning_start: "ilbumi/ViTClfR34/model-46zk5jsf:latest"
training:
  checkpoints_folder: "./"
  gpus: 1
  max_epochs: 200
